#!/usr/bin/env bash

if [ -z "$ASK_API_URL" ] || [ -z "$ASK_MODEL" ] || [ -z "$ASK_API_KEY" ]
then 
	echo "Error: ASK_API_URL , ASK_MODEL and ASK_API_KEY must be set."
	exit 1
fi

#Command line arguments as prompts
args_prompt="$*"

#Piped inputs as prompts
piped_input=""
if [ ! -z 0 ]
then
	piped_input="$(cat)"
fi
